export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const PRODUCTS_REQUEST_FAIL = 'PRODUCTS_REQUEST_FAIL';
export const PRODUCTS_LOADED = 'PRODUCTS_LOADED';

export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_REQUEST_FAIL = 'PRODUCT_REQUEST_FAIL';
export const PRODUCT_LOADED = 'PRODUCT_LOADED';